[versions]
kotlinx-coroutines = "1.7.3"
springboot = "3.1.3"
spring-statemachine = "3.2.1"
jackson = "2.15.2"
drift = "1.21"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

springboot-base = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springboot" }
springboot-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot" }
springboot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springboot" }
springboot-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springboot" }
springboot-undertow = { module = "org.springframework.boot:spring-boot-starter-undertow", version.ref = "springboot" }
springboot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springboot" }
springboot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springboot" }
springboot-es = { module = "org.springframework.boot:spring-boot-starter-data-elasticsearch", version.ref = "springboot" }

springboot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot" }

spring-statemachine-starter = { module = "org.springframework.statemachine:spring-statemachine-starter", version.ref = "spring-statemachine" }

jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

guava = { module = "com.google.guava:guava", version = "31.1-jre" }

thrift-lib = { module = "org.apache.thrift:libthrift", version = "0.17.0" }

ms-thrifty = { module = "com.microsoft.thrifty:thrifty-runtime-jvm", version = "3.1.0" }

drift-client = { module = "io.airlift.drift:drift-client", version.ref = "drift" }
drift-server = { module = "io.airlift.drift:drift-server", version.ref = "drift" }
drift-transport-netty = { module = "io.airlift.drift:drift-transport-netty", version.ref = "drift" }

[bundles]