[versions]
kotlinx-coroutines = "1.5.2"
springboot = "2.5.4"
spring-statemachine = "2.5.0"
jackson = "2.12.4"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

springboot-base = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springboot" }
springboot-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot" }
springboot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springboot" }
springboot-undertow = { module = "org.springframework.boot:spring-boot-starter-undertow", version.ref = "springboot" }
springboot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springboot" }
springboot-es = { module = "org.springframework.boot:spring-boot-starter-data-elasticsearch", version.ref = "springboot" }

springboot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot" }

spring-statemachine-starter = { module = "org.springframework.statemachine:spring-statemachine-starter", version.ref = "spring-statemachine" }

jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

guava = { module = "com.google.guava:guava", version = "30.1.1-jre" }

thrift-lib = { module = "org.apache.thrift:libthrift", version = "0.15.0" }

[bundles]