CREATE TABLE account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login       VARCHAR(64)                             NOT NULL,
    password    varchar(128)                            NOT NULL,
    nickname    VARCHAR(256)                            NOT NULL,
    avatar      VARCHAR(512)                            NOT NULL,
    add_time    TIMESTAMP,
    update_time TIMESTAMP,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_login UNIQUE (login);
