spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootz
    username: bootz
    password: 123456
    hikari:
      register-mbeans: true
  jpa:
    database: postgresql
    show-sql: true
    open-in-view: off

foo:
  service:
    url: localhost:8080